// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0Pec83o7HZapvurjOEbRS1BfbMgkmCo',
    appId: '1:362299203822:web:36b84327840e133b7713ff',
    messagingSenderId: '362299203822',
    projectId: 'practice-app-maaz',
    authDomain: 'practice-app-maaz.firebaseapp.com',
    storageBucket: 'practice-app-maaz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB16wLoZVoEdoeTYA_t644YFj6tE8Gupg',
    appId: '1:362299203822:android:e2a70218e1ab3a437713ff',
    messagingSenderId: '362299203822',
    projectId: 'practice-app-maaz',
    storageBucket: 'practice-app-maaz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwxVCFJWXzbsiYX0h4bkIGHP113GDVdrc',
    appId: '1:362299203822:ios:c072420a07612ad27713ff',
    messagingSenderId: '362299203822',
    projectId: 'practice-app-maaz',
    storageBucket: 'practice-app-maaz.firebasestorage.app',
    iosBundleId: 'com.example.practiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwxVCFJWXzbsiYX0h4bkIGHP113GDVdrc',
    appId: '1:362299203822:ios:c072420a07612ad27713ff',
    messagingSenderId: '362299203822',
    projectId: 'practice-app-maaz',
    storageBucket: 'practice-app-maaz.firebasestorage.app',
    iosBundleId: 'com.example.practiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0Pec83o7HZapvurjOEbRS1BfbMgkmCo',
    appId: '1:362299203822:web:bce68c47b72e307a7713ff',
    messagingSenderId: '362299203822',
    projectId: 'practice-app-maaz',
    authDomain: 'practice-app-maaz.firebaseapp.com',
    storageBucket: 'practice-app-maaz.firebasestorage.app',
  );
}
